name: Ruby Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.7.8"
          - "3.0.7"
          - "3.1.6"
          - "3.2.7"
          - "3.3.7"
          - "3.4.2"
          - "head"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run tests
        run: |
          bundle update
          bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
